inputSize=["20", "21", "22", "23", "24"]

plt.plot(inputSize, resultSeqTime)
plt.xlabel("InputSize")
plt.ylabel("Time")
plt.title("Execution Time (Model: Sequential)")
plt.savefig('./Sequential time.png')
plt.clf()
plt.plot(inputSize, resultslop)
plt.xlabel("InputSize")
plt.ylabel("Tp/T1")
plt.title("Time Ratio (Tp/T1)")
plt.savefig('./Time Ratio.png')
plt.clf()
plt.plot(inputSize, resultParallelTime)
plt.xlabel("InputSize")
plt.ylabel("Time")
plt.title("Execution Time (Model: Parallel)")
plt.savefig('./Parallel time.png')
plt.clf()